#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    echo "[*] Registering system command via update-alternatives..."
    update-alternatives --install /usr/bin/cppcrosshair-toolkit cppcrosshair-toolkit /usr/bin/cppcrosshair-editor 50
fi

exit 0
